### ISSUE TITLE
collada folder is missing textures

### ISSUE THREAD

**Issue by ShonFrazier** [mikelovesrobots/mmmm#1]
I fixed this locally by adding all the PNGs from fbx to collada. Then I wondered if softlinking to the textures from the collections might save space. Works here.

**Comment by mikelovesrobots** [comment]
Thanks for opening the issue. This is now fixed in: https://github.com/mikelovesrobots/mmmm/commit/25b30aa6bf3a276ca0a4ec9d98204147db8ab433 thanks to github user kfarr.
